apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  creationTimestamp: null
  name: source-git
spec:
  params:
  - name: url
    value: |
      https://github.com/marlon-gamez/getting-started.git
  type: git
status: {}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: skaffold-build
spec:
  inputs:
    resources:
    - name: source
      outputImageDir: ""
      targetPath: ""
      type: git
  steps:
  - args:
    - build
    - --filename
    - /workspace/source/skaffold.yaml
    - --profile
    - oncluster
    command:
    - skaffold
    image: gcr.io/k8s-skaffold/skaffold:v0.33.0
    name: run-build
    resources: {}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  creationTimestamp: null
  name: skaffold-deploy
spec:
  inputs:
    resources:
    - name: source
      outputImageDir: ""
      targetPath: ""
      type: git
  steps:
  - args:
    - deploy
    - --filename
    - /workspace/source/skaffold.yaml
    - --profile
    - oncluster
    command:
    - skaffold
    image: gcr.io/k8s-skaffold/skaffold:v0.33.0
    name: run-deploy
    resources: {}
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: skaffold-pipeline
spec:
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: skaffold-build-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    taskRef:
      name: skaffold-build
  - name: skaffold-deploy-task
    resources:
      inputs:
      - name: source
        resource: source-repo
    taskRef:
      name: skaffold-deploy
status: {}
---
