apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.FOO}}"
  artifacts:
  - image: gcr.io/first-week-244218/getting-started-CICD
    kaniko:
      buildContext:
        gcsBucket: skaffold-kaniko
      cache: {}
deploy:
  kubectl:
    manifests:
      - k8s-pod.yaml
